#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jan  7 20:54:30 2018

@author: emily
"""
import numpy as np
import matplotlib.pyplot as plt
n_groups = 4

plt.subplot(2,2,1)
index = np.arange(n_groups)  
bar_width = 0.2  
       
opacity = 0.4  
rects1 = plt.bar(index, L,bar_width,alpha=opacity, color='#DDDDDD',label=    'L',hatch = '/') 